pipeline {

    agent any

    options {
        buildDiscarder(logRotator(numToKeepStr: '2'))
        }

    environment {
        DOCKERHUB_USER = 'khannashiv'
        IMAGE_NAME = 'text-analyzer'
        IMAGE_TAG = "${BUILD_NUMBER}"
    }

    stages {

        stage('Checkout') {
            steps {
                git credentialsId: 'GitHub-auth-creds',
                url: 'https://github.com/khannashiv/Jenkins-Practice.git',
                branch: 'main'
            }
        }

        stage('Build Docker Image') {
            steps {
                script {
                    sh '''
                    echo 'Buid Docker Image'
                    ls -al /var/lib/jenkins/workspace/Test/Project-3/text-analyzer-app/
                    pwd
                    docker build -t ${DOCKERHUB_USER}/${IMAGE_NAME}:${IMAGE_TAG} -f Project-3/text-analyzer-app/Dockerfile Project-3/text-analyzer-app
                    '''
                }
            }
        }

        stage('Test Image') {
            steps {
                echo 'We will add test stage later.'
            }
        }


        stage('Docker login and Push the artifacts'){
           steps{
                withCredentials([usernamePassword(credentialsId: 'dockerhub-creds', passwordVariable: 'DOCKER_PASS')]) {
                script{
                    sh '''
                    echo 'Login to Docker Hub'
                    echo "$DOCKER_PASS" | docker login -u "$DOCKERHUB_USER" --password-stdin

                    echo 'Push to Repo'
                    docker push ${DOCKERHUB_USER}/${IMAGE_NAME}:${BUILD_NUMBER}
                    '''
                    }
                }
            }
        }

        stage('Cleanup') {
            steps {
                echo 'Cleaning up unused Docker images...'
                sh 'docker rmi ${DOCKERHUB_USER}/${IMAGE_NAME}:${IMAGE_TAG} || true'
            }
        }

    }

    post {
        success {
            echo "Build and push successful!"
        }
        failure {
            echo "Build failed. Check logs."
        }
    }
}
