pipeline {
    
    agent any 

    options {
        buildDiscarder(logRotator(numToKeepStr: '10'))
        }
    
    environment {
        IMAGE_TAG = "${BUILD_NUMBER}"
    }
    
    stages {
        
        stage('Checkout'){
           steps {
                git credentialsId: 'Git-auth-token', 
                url: 'https://github.com/khannashiv/Jenkins-Practice',
                branch: 'main'
           }
        }

        stage('Build Docker'){
            steps{
                script{
                    sh '''
                    echo 'Buid Docker Image'
                    ls -al /var/lib/jenkins/workspace/python-todo-app/
                    pwd
                    docker build -t khannashiv/cicd-e2e:${BUILD_NUMBER} -f Project-2/python-jenkins-argocd-k8s/Dockerfile .
                    '''
                }
            }
        }

        stage('Push the artifacts'){
           steps{
                withCredentials([usernamePassword(credentialsId: 'Docker-hub-creds', usernameVariable: 'DOCKER_USER', passwordVariable: 'DOCKER_PASS')]) {
                script{
                    sh '''
                    echo 'Login to Docker Hub'
                    echo "$DOCKER_PASS" | docker login -u "$DOCKER_USER" --password-stdin

                    echo 'Push to Repo'
                    docker push khannashiv/cicd-e2e:${BUILD_NUMBER}
                    '''
                    }
                }
            }
        }
        stage('Checkout K8S manifest SCM'){
            steps {
                git credentialsId: 'Git-auth-token', 
                url: 'https://github.com/khannashiv/CICD-manifests',
                branch: 'main'
            }
        }
        
        stage('Update K8S manifest & push to Repo'){
        environment {
                GIT_REPO_NAME = "CICD-manifests"
                GIT_USER_NAME = "khannashiv"
            }
            steps {
                script{
                    withCredentials([string(credentialsId: 'Git-auth-token', variable: 'GITHUB_TOKEN')]) {
                        sh '''
                            echo "Cloning target repo..."
                            rm -rf target-repo
                            git clone https://${GITHUB_TOKEN}@github.com/${GIT_USER_NAME}/${GIT_REPO_NAME}.git target-repo

                            echo "Modifying deployment.yaml in source repo"
                            sed -i "s/v1/${BUILD_NUMBER}/g" Project-2/python-jenkins-argocd-k8s/deploy/deploy.yaml
                            cat Project-2/python-jenkins-argocd-k8s/deploy/deploy.yaml

                            echo "Copying updated deploy.yaml to target repo"
                            cp Project-2/python-jenkins-argocd-k8s/deploy/deploy.yaml target-repo/Project-2/python-jenkins-argocd-k8s/deploy/

                            cd target-repo
                            git config user.email "khannashiv94@gmail.com"
                            git config user.name "Shiv"

                            git add Project-2/python-jenkins-argocd-k8s/deploy/deploy.yaml
                            git commit -m "Updated the deploy.yaml | Jenkins Pipeline" || echo "Nothing to commit"
                            git push origin main || echo "Nothing to push"
                        '''                        
                    }
                }
            }
        }
    }
}
