pipeline {
    
    agent any 
    
    environment {
        IMAGE_TAG = "${BUILD_NUMBER}"
    }
    
    stages {
        
        stage('Checkout'){
           steps {
                git credentialsId: 'Git-auth-token', 
                url: 'https://github.com/khannashiv/Jenkins-Practice',
                branch: 'main'
           }
        }

        stage('Build Docker'){
            steps{
                script{
                    sh '''
                    echo 'Buid Docker Image'
                    docker build -t khannashiv/cicd-e2e:${BUILD_NUMBER} .
                    '''
                }
            }
        }

        stage('Push the artifacts'){
           steps{
                script{
                    sh '''
                    echo 'Push to Repo'
                    docker push khannashiv/cicd-e2e:${BUILD_NUMBER}
                    '''
                }
            }
        }
        
        stage('Checkout K8S manifest SCM'){
            steps {
                git credentialsId: 'Git-auth-token', 
                url: 'https://github.com/khannashiv/CICD-manifests',
                branch: 'main'
            }
        }
        
        stage('Update K8S manifest & push to Repo'){
        environment {
                GIT_REPO_NAME = "CICD-manifests"
                GIT_USER_NAME = "khannashiv"
            }
            steps {
                script{
                    withCredentials([string(credentialsId: 'Git-auth-token', variable: 'GITHUB_TOKEN')]) {
                        sh '''
                        cat deploy.yaml
                        echo "Updating deployment.yml with image tag ${BUILD_NUMBER}"

                        export GIT_DIR=$WORKSPACE/.git
                        export GIT_WORK_TREE=$WORKSPACE
                        git config user.email "khannashiv94@gmail.com"
                        git config user.name "Shiv"

                        sed -i "s/v1/${BUILD_NUMBER}/g" Project-2/python-jenkins-argocd-k8s/deploy/deploy.yaml
                        cat deploy.yaml

                        git add deploy.yaml
                        git commit -m 'Updated the deploy yaml | Jenkins Pipeline'
                        git remote -v
                        git push https://${GITHUB_TOKEN}@github.com/${GIT_USER_NAME}/${GIT_REPO_NAME} HEAD:main || echo "Nothing to push"

                        '''                        
                    }
                }
            }
        }
    }
}
