apiVersion: v1
kind: Service
metadata:
  name: text-analyzer-app-service
spec:
  type: NodePort
  selector:
    app: text-analyzer-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
      nodePort: 31001